#!/bin/bash

CUDA_VISIBLE_DEVICES=0 python train_rnacompete_2009.py
CUDA_VISIBLE_DEVICES=0 python train_rnacompete_2009_mixed.py

CUDA_VISIBLE_DEVICES=0 python validation_rnacompete_2009.py
CUDA_VISIBLE_DEVICES=0 python validation_rnacompete_2009_mixed.py

CUDA_VISIBLE_DEVICES=0 python test_rnacompete_2009.pyru
CUDA_VISIBLE_DEVICES=0 python test_rnacompete_2009_mixed.py

CUDA_VISIBLE_DEVICES=0 python plot_rnacompete_2009_mixed_saliency.py
CUDA_VISIBLE_DEVICES=0 python plot_rnacompete_2009_mixed_motifs.py
CUDA_VISIBLE_DEVICES=0 python plot_rnacompete_2009_ensemble_saliency.py
